### ISSUE TITLE
Version of Game that can be directly cloned

### ISSUE THREAD

**Issue by BaileyMillerSSI** [JuDelCo/Command-Ant-Conquer#1]
I really love the design of the game and the gameplay I was really sad to see that I cannot directly clone this game though because it won't build because of missing references. 

Is there any way you could provide this code so that I could build it myself?

**Comment by JuDelCo** [comment]
Sorry, the original game relies in several paid assets from the store. I can't provide these in a public repository

**Comment by JuDelCo** [comment]
PS: Just for completion, at the bottom of the README it can be read:

"The following Addons have been removed: AmplifyColor, DOTweenPro, Rewired"
